Add Python 3 support
kakao-arena/shopping-classification pull request #3
Opened 2018-11-10 16:45 UTC by chiwanpark

Python 3 지원을 위해 아래 사항을 수정했습니다.
* `six` 라이브러리 추가 (py2/3 호환용, MIT license)
* 코드가 py3에서도 동작하도록 수정
* `y_vocab.cPickle` 파일 다시 만들어야하는 부분 README에 추가

기타 수정 사항
* `config.json`의 오타 수정 (`preidct` -> `predict`)

2018-11-10 16:49 UTC, ummae commented
@chiwanpark 👍 
가능하다면 `y_vocab.cPickle` 생성한 파일도 이름이 겹치지 않도록 해서 같이 포함하면 좋을 것 같아요.

2018-11-11 02:01 UTC, GzuPark commented on config.json
> +    "num_predict_workers": 2,
감사합니다 👍

2018-11-11 03:39 UTC, chiwanpark commented
@ummae Python 3에서 사용할 `y_vocab.py3.cPickle` 파일 추가했습니다. 코드에서도 자동으로 Python 3인 경우 해당 파일을 불러오도록 수정했어요.

2018-11-11 04:36 UTC, GzuPark commented
@chiwanpark 👏 + README.md의 실행방법 4. 에서도 안내를 해주는게 좋지 않을까요?

2018-11-14 11:33 UTC, ummae requested changes
@chiwanpark

2018-11-14 11:33 UTC, ummae commented on data.py
> +import mmh3
버저닝을 하는 게 좋을 것 같습니다. python2로 사용중이던 사람들은 해시 값이 달라져서 코드 업데이트 후에는 기존 데이터를 사용못하게 되네요.

```
hash = lambda x: mmh3.hash(x, seed=17) if six.PY3 else hash

2018-11-15 01:03 UTC, chiwanpark commented on data.py
> +import mmh3
@ummae 해당 부분 수정했습니다.

2018-11-22 02:46 UTC, chiwanpark commented
위 코드로 학습시킨 모델로 dev 계산하여 채점하면 아래와 같은 점수를 얻을 수 있습니다.

* Python 2: 0.851424
* Python 3: 0.845507

버전에 따른 점수 차이는 Python 버전 별 해시 함수 차이(built-in hash vs mmh3)로 생각됩니다.

2018-11-22 06:21 UTC, ummae commented
👍

2018-11-22 06:21 UTC, ummae approved these changes

2018-11-22 06:21 UTC, merged